# General settings
title: Yousef Farahat
author: Yousef Farahat
logo: images/logo_Yousef Farahat.png
#copyright: Delft University of Technology
#book_version: "1.0.0"

# Execute notebooks when building
execute:
  execute_notebooks: auto

# START DRAFT
html:
  comments:
    hypothesis: true
# END DRAFT
  
sphinx:
  local_extensions:
    apastyle: _ext/
    bracket_citation_style: _ext/
  extra_extensions:
    - sphinx_exercise
  config:
    bibtex_reference_style: author_year_round
    bibtex_default_style: myapastyle
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
bibtex_bibfiles: 
  - references.bib
